=== alyleui/Angular-Module-Builder-CLI/export/config/schema.json
{
  "$schema": "http://json-schema.org/schema",
  "title": "Angular Module Builder CLI",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "root": {
      "type": "string",
      "title": "The Root Schema",
      "default": "src/lib"
    },
    "outDir": {
      "type": "string",
      "title": "The Outdir Schema",
      "default": "dist-amb"
    },
    "version": {
      "type": "string",
      "title": "The Version Schema"
    },
    "pkg": {
      "type": "string",
      "title": "The Pkg Schema",
      "default": "{root}/packpage.json"
    },
    "es2015": {
      "type": "string",
      "title": "The Es2015 Schema",
      "default": "{root}/tsconfig-build.json"
    },
    "esm": {
      "type": "string",
      "title": "The Esm Schema",
      "default": "{root}/tsconfig-esm.json"
    },
    "libs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Module name"
          },
          "dir": {
            "type": "string",
            "title": "Directory where the module container is",
            "description": "Example:\n. === {name}/{name}\nmy-module === {root}/my-module",
            "default": "{name}"
          },
          "pkg": {
            "type": "string",
            "title": "File package in dir, {root}/{dir}/package.json",
            "default": "package.json"
          },
          "version": {
            "type": "string",
            "title": "Version for this module",
            "default": "{version}"
          },
          "es2015": {
            "type": "string",
            "title": "es2015 config in dir, {root}/{dir}/tsconfig-build.json",
            "default": "ts.config-build"
          },
          "esm": {
            "type": "string",
            "title": "esm config in dir, {root}/{dir}/ts.config-esm.json",
            "default": ""
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "globals": {
      "type": "object",
      "title": "Globals for rollup"
    }
  }, 
  "required": [
    "version",
    "libs",
    "root",
    "outDir"
  ],
  "additionalProperties": false
}

=== alyleui/Angular-Module-Builder-CLI/.amb.json
{
  "$schema": "./export/config/schema.json",
  "root": "src/lib",
  "version": "0.1.1-beta.0",
  "outDir": "dist-amb",
  "libs": [
    {
      "name": "my-module"
    },
    {
      "name": "example-demo/core",
      "dir": "example-demo"
    },
    {
      "name": "root",
      "dir": "/"
    }
  ],
  "globals": {
    "@angular/core": "ng.core",
    "@angular/platform-browser": "ng.platformBrowser",
    "@angular/common": "ng.common",
    "@angular/common/http": "ng.common.http",
    "@angular/forms": "ng.forms",
    "@angular/http": "ng.http",
    "@angular/animations": "ng.animations",
    "rxjs": "Rx",
    "rxjs/Observable": "Rx",
    "rxjs/Subject": "Rx",
    "rxjs/Observer": "Rx",
    "rxjs/Subscription": "Rx",
    "rxjs/BehaviorSubject": "Rx",
    "rxjs/observable/merge": "Rx.Observable",
    "rxjs/operator/share": "Rx.Observable.prototype",
    "rxjs/operator/observeOn": "Rx.Observable.prototype",
    "rxjs/observable/of": "Rx.Observable.prototype",
    "rxjs/operator/combineLatest": "Rx.Observable.prototype",
    "rxjs/operator/merge": "Rx.Observable.prototype",
    "rxjs/operator/map": "Rx.Observable.prototype",
    "rxjs/operator/auditTime": "Rx.Observable.prototype",
    "rxjs/operator/switchMap": "Rx.Observable.prototype",
    "rxjs/operator/do": "Rx.Observable.prototype",
    "rxjs/operator/skip": "Rx.Observable.prototype",
    "rxjs/operator/take": "Rx.Observable.prototype",
    "rxjs/operator/toArray": "Rx.Observable.prototype",
    "rxjs/operator/toPromise": "Rx.Observable.prototype",
    "rxjs/add/operator/map": "Rx.Observable.prototype",
    "rxjs/add/operator/scan": "Rx.Observable.prototype",
    "rxjs/add/operator/skip": "Rx.Observable.prototype",
    "rxjs/add/operator/do": "Rx.Observable.prototype",
    "rxjs/add/operator/distinctUntilChanged": "Rx.Observable.prototype",
    "rxjs/add/operator/filter": "Rx.Observable.prototype",
    "rxjs/add/operator/skipUntil": "Rx.Observable.prototype",
    "rxjs/add/operator/skipWhile": "Rx.Observable.prototype",
    "rxjs/add/operator/withLatestFrom": "Rx.Observable.prototype",
    "rxjs/add/operator/switchMap": "Rx.Observable.prototype",
    "rxjs/add/observable/merge": "Rx.Observable",
    "rxjs/add/observable/of": "Rx.Observable.prototype",
    "rxjs/add/observable/fromPromise": "Rx.Observable.prototype",
    "rxjs/add/operator/delay": "Rx.Observable",
    "rxjs/add/operator/debounce": "Rx.Observable",
    "rxjs/add/operator/share": "Rx.Observable",
    "rxjs/observable/fromEvent": "Rx.Observable",
    "rxjs/observable/from": "Rx.Observable",
    "rxjs/operator": "Rx.Observable.prototype",
    "rxjs/scheduler/queue": "Rx.Scheduler",
    "chroma-js": "chroma"
  }
}
